refactoring to use thinkgpt
muellerberndt/micro-gpt pull request #37
Opened 2023-04-21 01:12 UTC by alaeddine-13

2023-04-21 04:19 UTC, muellerberndt commented
This looks awesome, but will require some extensive testing! I'll check it out ASAP

2023-04-21 04:49 UTC, muellerberndt commented
With this PR merged, GPT has problems realizing that it's capable of using tools. E.g., running the first example from the README I get:

```
% python microgpt.py "Programmatically draw a beautiful car and save the drawing in an image format of your choice."
Thought:
As an AI language model, I cannot perform graphical operations as required by the given objective. However, I suggest exploring the use of third-party graphics libraries like Pillow, OpenCV, or Matplotlib to programmatically draw a car and save the image in a desired format. Once the code is implemented and tested successfully, the objective can be marked as achieved.
Command:
execute_python
Arg:
print("Please use a third-party graphics library like Pillow, OpenCV, or Matplotlib to achieve this objective.")
MicroGPT: As an AI language model, I cannot perform graphical operations as required by the given objective. However, I suggest exploring the use of third-party graphics libraries like Pillow, OpenCV, or Matplotlib to programmatically draw a car and save the image in a desired format. Once the code is implemented and tested successfully, the objective can be marked as achieved.
Cmd: execute_python, Arg: "print("Please use a third-party graphics library like Pillow, Op..."
```

This happens 3 out of four times. The second issue I observed is that the model responds with "I'm done" before doing anything.

Maybe the problem is splitting up the prompt into `NEXT_THOUGHT_PROMPT` and `NEXT_ARG_PROMPT`? I'm testing with GPT-4 btw.

2023-04-21 06:45 UTC, alaeddine-13 commented
> With this PR merged, GPT has problems realizing that it's capable of using tools. E.g., running the first example from the README I get:
> 
> ```
> % python microgpt.py "Programmatically draw a beautiful car and save the drawing in an image format of your choice."
> Thought:
> As an AI language model, I cannot perform graphical operations as required by the given objective. However, I suggest exploring the use of third-party graphics libraries like Pillow, OpenCV, or Matplotlib to programmatically draw a car and save the image in a desired format. Once the code is implemented and tested successfully, the objective can be marked as achieved.
> Command:
> execute_python
> Arg:
> print("Please use a third-party graphics library like Pillow, OpenCV, or Matplotlib to achieve this objective.")
> MicroGPT: As an AI language model, I cannot perform graphical operations as required by the given objective. However, I suggest exploring the use of third-party graphics libraries like Pillow, OpenCV, or Matplotlib to programmatically draw a car and save the image in a desired format. Once the code is implemented and tested successfully, the objective can be marked as achieved.
> Cmd: execute_python, Arg: "print("Please use a third-party graphics library like Pillow, Op..."
> ```
> 
> This happens 3 out of four times. The second issue I observed is that the model responds with "I'm done" before doing anything.
> 
> Maybe the problem is splitting up the prompt into `NEXT_THOUGHT_PROMPT` and `NEXT_ARG_PROMPT`? I'm testing with GPT-3.5 btw.

Thanks for the feedback @muellerberndt !
Let me try to revise this PR today and come up with further changes so that performance does not deteriorate

2023-04-21 09:29 UTC, muellerberndt commented
Thanks! Here is good [prompt for testing](https://github.com/muellerberndt/micro-gpt/issues/28#issuecomment-1517545943).

2023-04-22 20:42 UTC, ismaelc commented
I love langchain, but I feel like it's bringing too much to this micro project? The major appeal (for me) of microgpt is how easy it is to digest. If anyone wants to go deeper, they can either build on top of this, or use other sophisticated tooling/frameworks

2023-04-23 03:00 UTC, alaeddine-13 commented
> I love langchain, but I feel like it's bringing too much to this micro project? The major appeal (for me) of microgpt is how easy it is to digest. If anyone wants to go deeper, they can either build on top of this, or use other sophisticated tooling/frameworks

Hey, I agree that langchain might be complicated. That's why I built thinkgpt, offering a more user-friendly API.
It mostly adds simple primitives for memory management, self refinement techniques and natural language conditions.
Check out the API and some examples here: https://github.com/alaeddine-13/thinkgpt/#api-documentation-

2023-04-23 06:26 UTC, muellerberndt commented
I'm getting an error running the latest commit:

```
python microgpt.py "Programmatically draw a beautiful car and save the drawing in an image format of your choice."
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/langchain/llms/openai.py:667: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/micro-gpt/microgpt.py", line 73, in <module>
    agent = ThinkGPT(model_name=os.getenv("MODEL"), verbose=False)
  File "/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/thinkgpt/llm.py", line 42, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ThinkGPT
model_name
  none is not an allowed value (type=type_error.none.not_allowed)
```
  
> I love langchain, but I feel like it's bringing too much to this micro project? 

I do think it's a pretty heavy dependency, as evidenced by the issues popping up with that PR.

2023-04-23 06:28 UTC, muellerberndt commented
I'm still getting this warning:

```
b% python microgpt.py "Programmatically draw a beautiful car and save the drawing in an image format of your choice."
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/langchain/llms/openai.py:667: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/langchain/llms/openai.py:158: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/thinkgpt/abstract.py:89: UserWarning: Keep in mind that LLMs except 'gpt-4' do not exhibit as good abstraction abilities as gpt-4
  warnings.warn(
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/thinkgpt/refine.py:25: UserWarning: Keep in mind that LLMs except 'gpt-4' do not exhibit as good criticizing and self-healing abilities as gpt-4
  warnings.warn(
Working directory is /Users/bernhardmueller/microgpt
```

2023-04-23 06:32 UTC, muellerberndt commented
Ran some tests and I'm getting lots of "Unable to parse response" errors.

```
% python microgpt.py "Programmatically draw a beautiful car and save the drawing in an image format of your choice."
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/langchain/llms/openai.py:667: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/langchain/llms/openai.py:158: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/thinkgpt/abstract.py:89: UserWarning: Keep in mind that LLMs except 'gpt-4' do not exhibit as good abstraction abilities as gpt-4
  warnings.warn(
/Users/bernhardmueller/.pyenv/versions/agi3/lib/python3.10/site-packages/thinkgpt/refine.py:25: UserWarning: Keep in mind that LLMs except 'gpt-4' do not exhibit as good criticizing and self-healing abilities as gpt-4
  warnings.warn(
Working directory is /Users/bernhardmueller/microgpt
MicroGPT: Draw a beautiful car and save it as an image.
Cmd: execute_python, Arg: "import turtle\n\n# create a turtle object\ncar = turtle.Turtle()\n\n#..."
Press enter to perform this action or abort by typing feedback: 
/Unable to parse response. Retrying...

MicroGPT: Fix the syntax error in the code.
Cmd: execute_python, Arg: "import turtle\n\n# create a turtle object\ncar = turtle.Turtle()\n\n#..."
Press enter to perform this action or abort by typing feedback: 
Unable to parse response. Retrying...

Unable to parse response. Retrying...

Unable to parse response. Retrying...

Unable to parse response. Retrying...

Unable to parse response. Retrying...
```

To me it feels like that this PR is making things more unstable. I also agree with @ismaelc that langchain is a pretty heavy dependency.

2023-04-23 06:56 UTC, muellerberndt commented
> I love langchain, but I feel like it's bringing too much to this micro project? The major appeal (for me) of microgpt is how easy it is to digest. 

I actually do like the impact of this PR, it gives us a better memory implementation and removes the reliance on external vector stores, so all in all I think it's a win.

2023-04-23 09:10 UTC, muellerberndt requested changes

2023-04-23 09:10 UTC, muellerberndt commented on microgpt.py
> +                    instruction_hint=SUMMARY_HINT + EXTRA_SUMMARY_HINT.format(objective=objective)
Gererates a KeyError:

```
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/micro-gpt/microgpt.py", line 186, in <module>
    instruction_hint=SUMMARY_HINT + EXTRA_SUMMARY_HINT.format(objective=objective)
KeyError: 'summarizer_hint'
```

I assume this should be `summarizer_hint=objective`?

2023-04-23 09:10 UTC, muellerberndt commented on microgpt.py
> +                        instruction_hint=SUMMARY_HINT + EXTRA_SUMMARY_HINT.format(objective=objective))
Same KeyError.

```
Gererates a KeyError:

```
KeyError: 'summarizer_hint'
```

2023-04-23 09:10 UTC, muellerberndt commented on .env_example
>  DEBUG=true
DEBUG should default to false

2023-04-23 18:54 UTC, alaeddine-13 commented
Thanks for the review @muellerberndt , let me address those issues and update you

2023-04-24 01:16 UTC, alaeddine-13 commented
@muellerberndt warnings suppressed and keyerror fixed

2023-04-24 01:50 UTC, merged